name: pandora
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.7.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get_cli: ^1.5.0
  speech_to_text: ^2.3.0
  highlight_text: ^0.7.2
  avatar_glow: ^1.2.0

  get: 4.1.4
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/.
    - assets/images/

# see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: BerkshireSwash
      fonts:
        - asset: assets/fonts/BerkshireSwash-Regular.ttf
        
    - family: NunitoSans
      fonts:
        - asset: assets/fonts/NunitoSans-Regular.ttf